version: 2
jobs: 
  build_one:
    docker: 
    - image: circleci/node:4.8.2
    steps:
    - checkout
    - run: echo "A first hello"
  build_two:
    docker: 
    - image: circleci/node:4.8.2
    steps:
    - checkout
    - run: echo "A more familiar hello"

workflows:
  version: 2
  one_and_two:
    jobs: 
      - build_one
      - build_two